### ISSUE TITLE
why not use gitBook for documentation this cleaner than FrostDoc ?

### ISSUE THREAD

**Issue by AzaleeX** [PowerNukkitX/PNX-Document#6]
if I can do it I'm keen to do it I'm just asking for an agreement / a refusal of my request

**Comment by SuperIceCN** [comment]
First of all, the open-source version of GitBook is **deprecated** now and GitBook is a proprietary software.  
We won't use Proprietary software, which prevents others from contributing freely and fairly.  

GitBook does not have the following functions:  
- Fast deploy (Open source version of GitBook takes much longer time to deploy)
- Fast renderer (It taks more than 10 times longer for GitBook to render the documents)
- Custom markdown syntax. (We use some custom syntax in document)
- Fully self-hosted search.
- Geographical divided Google Analytics support. (This helps me to know which page is popular and how to make them better)
- Integrated JavaScript and image size optimization. (It's annoying to repeatedly teach others how to optimize size everytime)
- Automatic SEO optimization

In order for others to understand FrostDoc, there is a detailed user manual in its repository.  

My years of open-source experience and team project experience have taught me one thing: popular ones may not necessarily be suitable, but the suitable ones are the best.
